server:
  host: 192.168.31.94
  port: 8060
  mode: dev
ssl:
  enable: false
  key: keystring
  pem: temp/pem.pem
log:
  level: debug
  maxSize: 1024
  maxAge: 30
  maxBackups: 10
  localtime: 1
  compress: 1
  path: log/comet.log
db:
  type: postgres
  dsn: host=localhost user=postgres password=123456 dbname=comet port=5432 sslmode=disable TimeZone=Asia/Shanghai
  maxOpenConn: 20000
  maxIdleConn: 0
  connMaxLifetime: 60
jwt:
  expires: 60
  secret: xxx
  issuer: comet
