server:
  host: localhost
  port: 8060
  mode: dev
ssl:
  enable: false
  key: keystring
  pem: temp/pem.pem
log:
  level: info
  maxsize: 1024
  maxage: 30
  maxbackups: 10
  localtime: 1
  compress: 1
  console: 1
  path: log/comet.log
jwt:
  expires: 60
  secret: xxx
  issuer: comet
